"""Fill HogUI Atlas's curated loot file (HogHeals_Atlas/Data/Loot.lua) from a CSV of VERIFIED drops.

    python dev/atlas_import.py drops.csv                 # dry run: says what it would write, writes nothing
    python dev/atlas_import.py drops.csv --write         # writes Data/Loot.lua
    python dev/atlas_import.py drops.csv --write --allow-new-boss

CSV columns (header row required): dungeon_key,boss_name,item_id,source
  dungeon_key  a key from Data/Dungeons.lua (vc, wc, lordaeron ...)
  boss_name    exactly as in Data/Dungeons.lua; a boss the list does not know needs --allow-new-boss
  item_id      a positive number
  source       where the drop was verified ("seen 2026-11-05 Hog", a URL ...). Required: a row nobody can trace
               does not go in.

Rules: every bad row is reported with its line number and the run FAILS (exit 1) - a half-imported file is worse
than none. Rows are de-duplicated and written sorted, so the same CSV always gives the same file. Capped at 20000
rows. The file is rewritten whole; an empty CSV (header only) writes the empty table back.
"""
from __future__ import annotations

import argparse
import csv
import pathlib
import sys
from collections import defaultdict

from lupa.lua51 import LuaRuntime

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "HogHeals_Atlas" / "Data"
CAP = 20000
COLUMNS = ["dungeon_key", "boss_name", "item_id", "source"]


def dungeons() -> dict[str, set[str]]:
    """{ key: { boss names incl. rares } } read from the real Data/Dungeons.lua."""
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute("HogHealsAtlas = {}")
    lua.execute((DATA / "Dungeons.lua").read_text(encoding="utf-8"))
    out = {}
    for d in lua.eval("HogHealsAtlas.Data.Dungeons").values():
        names = set(d["bosses"].values())
        if d["rares"] is not None:
            names |= set(d["rares"].values())
        out[d["key"]] = names
    return out


def read(path: pathlib.Path, allow_new_boss: bool = False):
    """(table, sources, problems). table = { dungeon: { boss: sorted item ids } }."""
    known = dungeons()
    table: dict[str, dict[str, set[int]]] = defaultdict(lambda: defaultdict(set))
    sources: set[str] = set()
    problems: list[str] = []
    with path.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None or [f.strip() for f in reader.fieldnames] != COLUMNS:
            return {}, set(), [f"header must be exactly: {','.join(COLUMNS)} (got {reader.fieldnames})"]
        for n, row in enumerate(reader, start=2):
            if n - 1 > CAP:
                problems.append(f"more than {CAP} rows: stopped")
                break
            key = (row.get("dungeon_key") or "").strip()
            boss = (row.get("boss_name") or "").strip()
            raw = (row.get("item_id") or "").strip()
            src = (row.get("source") or "").strip()
            if not any((key, boss, raw, src)):
                continue
            if key not in known:
                problems.append(f"line {n}: unknown dungeon_key '{key}'")
                continue
            if not boss or len(boss) > 60 or any(c in boss for c in ';|"\\') or any(ord(c) < 32 for c in boss):
                problems.append(f"line {n}: bad boss_name '{boss}'")
                continue
            if boss not in known[key] and not allow_new_boss:
                problems.append(f"line {n}: '{boss}' is not a boss of '{key}' in Data/Dungeons.lua (--allow-new-boss to accept)")
                continue
            if not raw.isdigit() or not (0 < int(raw) <= 9999999):
                problems.append(f"line {n}: item_id '{raw}' is not a positive number")
                continue
            if not src:
                problems.append(f"line {n}: no source - a drop nobody can trace does not go in")
                continue
            table[key][boss].add(int(raw))
            sources.add(src)
    return {k: {b: sorted(v) for b, v in bosses.items()} for k, bosses in table.items()}, sources, problems


def render(table, sources, csv_name: str) -> str:
    rows = sum(len(items) for bosses in table.values() for items in bosses.values())
    out = [
        "-- Curated drops: Curated[dungeonKey][bossName] = { itemID, ... }. Badge in the window: \"reported\".",
        "--",
        "-- GENERATED by dev/atlas_import.py - do not edit by hand, edit the CSV and run the tool.",
        f"-- From: {csv_name}   rows: {rows}   sources: {len(sources)}",
        "-- Every row was verified in play or by a named source; item ids are never written from memory.",
        "local A = HogHealsAtlas",
        "A.Data = A.Data or {}",
        "A.Data.Curated = {",
    ]
    for key in sorted(table):
        out.append(f"  {key} = {{")
        for boss in sorted(table[key]):
            ids = ", ".join(str(i) for i in table[key][boss])
            out.append(f'    ["{boss}"] = {{ {ids} }},')
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv", type=pathlib.Path)
    ap.add_argument("--write", action="store_true", help="write Data/Loot.lua (default: dry run)")
    ap.add_argument("--allow-new-boss", action="store_true", help="accept bosses Data/Dungeons.lua does not list")
    ap.add_argument("--out", type=pathlib.Path, default=DATA / "Loot.lua", help=argparse.SUPPRESS)
    args = ap.parse_args(argv)
    if not args.csv.exists():
        print(f"FAIL: no such file {args.csv}", file=sys.stderr)
        return 1
    table, sources, problems = read(args.csv, args.allow_new_boss)
    if problems:
        for p in problems:
            print("FAIL:", p, file=sys.stderr)
        print(f"FAIL: {len(problems)} bad row(s); nothing written", file=sys.stderr)
        return 1
    rows = sum(len(items) for bosses in table.values() for items in bosses.values())
    text = render(table, sources, args.csv.name)
    print(f"{rows} drop(s), {sum(len(b) for b in table.values())} boss(es), {len(table)} dungeon(s), {len(sources)} source(s)")
    if not args.write:
        print("DRY RUN: nothing written. Add --write to write", args.out.name)
        return 0
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
