# dev/atlas_import.py: the curated loot file is only ever written from a CSV of traceable drops.
import pathlib
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "dev"))
import atlas_import  # noqa: E402

from atlas_helpers import boot, vals  # noqa: E402

HEADER = "dungeon_key,boss_name,item_id,source\n"


def write(tmp_path, body, header=HEADER):
    p = tmp_path / "drops.csv"
    p.write_text(header + body, encoding="utf-8")
    return p


def test_dungeon_list_is_read_from_the_real_data_file():
    d = atlas_import.dungeons()
    assert "Edwin VanCleef" in d["vc"] and "Miner Johnson" in d["vc"] and d["lordaeron"] == set()
    assert len(d) >= 27


def test_dry_run_is_the_default_and_writes_nothing(tmp_path, capsys):
    csv = write(tmp_path, "vc,Cookie,5198,seen 2026-11-05 Hog\n")
    out = tmp_path / "Loot.lua"
    assert atlas_import.main([str(csv), "--out", str(out)]) == 0
    assert not out.exists()
    assert "DRY RUN" in capsys.readouterr().out


def test_write_is_sorted_deduplicated_and_loads_in_the_addon(tmp_path, lua):
    csv = write(tmp_path, (
        "wc,Kresh,13245,seen 2026-11-06 Hog\n"
        "vc,Cookie,5198,seen 2026-11-05 Hog\n"
        "vc,Cookie,5197,seen 2026-11-05 Hog\n"
        "vc,Cookie,5198,second report\n"                       # the same drop twice
        "vc,Edwin VanCleef,5191,seen 2026-11-05 Hog\n"
        ",,,\n"                                                # an empty line is not an error
    ))
    out = tmp_path / "Loot.lua"
    assert atlas_import.main([str(csv), "--write", "--out", str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert text.index("vc = {") < text.index("wc = {")
    assert '["Cookie"] = { 5197, 5198 },' in text and '["Edwin VanCleef"] = { 5191 },' in text
    assert "rows: 4   sources: 3" in text and "GENERATED" in text
    again = tmp_path / "Loot2.lua"
    atlas_import.main([str(csv), "--write", "--out", str(again)])
    assert again.read_text(encoding="utf-8") == text                                  # same CSV, same file
    # the real addon reads it: drops show as "reported" and have a source
    boot(lua)
    lua.execute(text)
    rows = vals(lua.eval('HogHealsAtlas.Store.GetBossLoot("vc", "Cookie")'))
    assert [(r["id"], r["src"]) for r in rows] == [(5197, "reported"), (5198, "reported")]
    lua.execute("HogHealsAtlas.Store.index = nil")
    assert lua.eval('(HogHealsAtlas.Store.SourceText(13245))') == "Kresh (Wailing Caverns)"


@pytest.mark.parametrize("row,why", [
    ("nowhere,Cookie,5198,seen\n", "unknown dungeon_key"),
    ("vc,Kresh,5198,seen\n", "is not a boss of 'vc'"),
    ("vc,Cookie,abc,seen\n", "not a positive number"),
    ("vc,Cookie,0,seen\n", "not a positive number"),
    ("vc,Cookie,-4,seen\n", "not a positive number"),
    ("vc,Cookie,5198,\n", "no source"),
    ("vc,,5198,seen\n", "bad boss_name"),
    ('vc,"Coo|kie",5198,seen\n', "bad boss_name"),
])
def test_one_bad_row_fails_the_whole_run_and_writes_nothing(tmp_path, capsys, row, why):
    csv = write(tmp_path, "vc,Cookie,5197,seen 2026-11-05 Hog\n" + row)
    out = tmp_path / "Loot.lua"
    assert atlas_import.main([str(csv), "--write", "--out", str(out)]) == 1
    err = capsys.readouterr().err
    assert why in err and "line 3" in err and "nothing written" in err
    assert not out.exists()


def test_wrong_header_and_missing_file_fail(tmp_path, capsys):
    csv = write(tmp_path, "vc,Cookie,5198,seen\n", header="dungeon,boss,item,source\n")
    assert atlas_import.main([str(csv)]) == 1
    assert "header must be exactly" in capsys.readouterr().err
    assert atlas_import.main([str(tmp_path / "missing.csv")]) == 1


def test_new_bosses_need_the_flag(tmp_path):
    csv = write(tmp_path, "lordaeron,The Abandoned,250001,seen 2026-11-05 Hog\n")
    out = tmp_path / "Loot.lua"
    assert atlas_import.main([str(csv), "--write", "--out", str(out)]) == 1
    assert atlas_import.main([str(csv), "--write", "--allow-new-boss", "--out", str(out)]) == 0
    assert '["The Abandoned"] = { 250001 },' in out.read_text(encoding="utf-8")


def test_header_only_writes_the_empty_table_back(tmp_path):
    csv = write(tmp_path, "")
    out = tmp_path / "Loot.lua"
    assert atlas_import.main([str(csv), "--write", "--out", str(out)]) == 0
    assert "A.Data.Curated = {\n}" in out.read_text(encoding="utf-8")


def test_the_shipped_file_is_still_empty():
    # nothing verified exists yet; this fails the day someone fills it by hand instead of through the tool
    text = (ROOT / "HogHeals_Atlas" / "Data" / "Loot.lua").read_text(encoding="utf-8")
    assert "A.Data.Curated = {}" in text or "GENERATED by dev/atlas_import.py" in text
